### ISSUE TITLE
Definir o contrato para a API de cliente

### ISSUE THREAD

**Issue by felipewind** [vic012/banco-click#1]
Olá @vic012 tudo bem? Ficou muito legal o README.md do projeto.

Que acha de começarmos com a API do cliente? Seria para o cliente se cadastrar no banco e depois disso poder abrir sua conta.

Pode ser no formato JSON?

Pensei em algo assim, que acha?
```ts
{ 
  id: number,
  usuario: string,
  senha: string,
  nome: string,
  email: string
}
```

Daí em cima disso, você criaria o CRUD com POST, GET, GET{id}, PUT{id} e DELETE{id}.

Que acha?

No POST eu não passo o id. Daí o backend geraria isto e devolveria na resposta.

**Comment by vic012** [comment]
Bom dia, ótima ideia, verdade eu não havia pensado nessa questão, de fato é lógico criar primeiro uma conta e realizar o login para só depois realizar aquelas funcionalidades, bem pensado

Mas acredito que consigo no formato do JSON sim.

**Comment by felipewind** [comment]
Legal @vic012 !
Essa API seria anterior à da conta. Seria para cadastrar o cliente no sistema. Depois desse cadastro, ele poderia abrir uma conta.

Que acha?

Se concordar com a ideia, o layout que eu propus está bom? Você gostaria de mexer em algo?

Se estiver de acordo, quando eu tiver um tempo vou começar a fazer o frontend com essa parte inicial do login do cliente no sistema.

Valeu!

**Comment by vic012** [comment]
Concordo completamente com o layout, já estou preparando a API para receber esse JSON do front-end.
Mas sem pressa, quando você puder ai.
Valeu Felipe.

**Comment by felipewind** [comment]
Fechado @vic012 
Acho que durante a semana que vem em devo terminar uma versão inicial.
Eu nunca programei com Python.
Vou precisar de um roteiro para colocar a sua API para rodar na minha máquina :)

**Comment by vic012** [comment]
Opá, sem problemas, @felipewind 
Com certeza vou lhe ajudar.
Vamos aprendendo juntos \o/
